#!/bin/bash

init() {
    echo "Init..."
    poetry env use python3.10
    poetry install
}

log_analyzer() {
    echo "Running log analyzer..."
    poetry run python src/log_analyzer.py $1 $2
}

if [[ "$1" = "init" ]]; then
    init
elif [[ "$1" = "log_analyzer" ]]; then
    log_analyzer $2 $3
fi