#!/bin/bash

deco() {
    poetry run python src/deco.py
}

init() {
    echo "Init..."
    poetry env use python3.10
    poetry install
}

poker() {
    echo "Running poker..."
    poetry run python src/poker.py
}

if [[ "$1" = "init" ]]; then
    init
elif [[ "$1" = "poker" ]]; then
    poker
elif [[ "$1" = "deco" ]]; then
    deco
fi
